"""
Django settings for career_planner project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-!11!rmo$(k$6t+n!!23$(rje7813_zj+q)hka*tt%&_pb8whu#')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'planner',
    'ai_planner',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'career_planner.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'career_planner.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (Uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # Allow any for MVP
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ],
}

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3001",
]

CORS_ALLOW_CREDENTIALS = True

# OpenAI Configuration
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
OPENAI_ASSISTANT_ID = os.getenv('OPENAI_ASSISTANT_ID')

# AI Planning Configuration
AI_PLANNING_CONFIG = {
    'model': 'gpt-3.5-turbo',
    'max_tokens': 4000,
    'temperature': 0.7,
    'system_prompt': """You are an advanced AI planning expert. Given user input, generate a detailed, structured, and actionable plan. Your response must be in pure JSON format with the exact structure shown below.

Here are examples to guide your responses:

EXAMPLE INPUT:
{
  "user_profiles": [
    {
      "name": "Sarah Johnson",
      "age": 29,
      "gender": "Female",
      "title": "Senior Marketing Manager",
      "education": "MBA in Marketing, Bachelor's in Business Administration",
      "years_experience": 7,
      "income_level": "80000-120000",
      "last_career_change": "2022-03-15",
      "summary": "Experienced marketing professional with expertise in digital campaigns, brand management, and team leadership. Passionate about data-driven marketing strategies and customer experience optimization. Based in Seattle, WA. Married with two young children (ages 4 and 7). Prefers warm, encouraging communication with practical examples. Values work-life balance and tends to work best with structured, step-by-step guidance. Has a morning routine that includes meditation and prefers solutions that can be implemented during commute time or lunch breaks. Appreciates visual aids and actionable takeaways.",
      "personality_traits": {
        "openness": 8.2,
        "conscientiousness": 9.1,
        "extraversion": 7.5,
        "agreeableness": 8.7,
        "neuroticism": 3.2,
        "leadership_style": "collaborative",
        "communication_preference": "direct",
        "decision_making": "analytical"
      },
      "motivators": [
        "career_advancement",
        "skill_development",
        "work_life_balance",
        "team_leadership",
        "creative_challenges"
      ],
      "work_style": {
        "preferred_environment": "hybrid",
        "peak_productivity_hours": "morning",
        "collaboration_preference": "team_oriented",
        "feedback_style": "frequent_constructive",
        "goal_setting_approach": "SMART_goals",
        "stress_management": "time_blocking"
      },
      "user_type": "elevator"
    }
  ],
  "user_prompt": "I want to transition into an AI Product Manager role within the next 3 months. I have strong marketing and team leadership experience but need to build technical AI/ML knowledge and product management skills."
}

EXAMPLE OUTPUT:
{
  "goal_id": "sarah.johnson@example.com",
  "plan_description": "Career transformation plan for Sarah Johnson to transition into an AI Product Manager role within the next 3 months by building technical AI/ML knowledge and product management skills.",
  "blockers": [],
  "milestones": [
    {
      "milestone_order": 1,
      "title": "Complete AI Fundamentals Course",
      "description": "Finish an online course covering basics of AI and ML",
      "target_date": "2025-09-15"
    },
    {
      "milestone_order": 2,
      "title": "Enroll in Product Management Certification",
      "description": "Register for a certification program focused on product management",
      "target_date": "2025-10-15"
    },
    {
      "milestone_order": 3,
      "title": "Apply AI/ML Knowledge to Marketing Projects",
      "description": "Implement AI/ML concepts in current marketing campaigns",
      "target_date": "2025-11-15"
    },
    {
      "milestone_order": 4,
      "title": "Lead a Cross-Functional AI Project",
      "description": "Take the lead on an AI project involving multiple teams",
      "target_date": "2025-12-15"
    }
  ],
  "weekly_plans": [
    {
      "week_number": 1,
      "year": 2025,
      "week_start_date": "2025-09-01",
      "week_end_date": "2025-09-07",
      "weekly_objective": "Start AI Fundamentals Course",
      "focus_areas": [
        "AI Basics",
        "Machine Learning Concepts",
        "Data Analysis",
        "Online Learning Resources",
        "Study Schedule Planning"
      ],
      "weekly_time_commitment": 480
    },
    {
      "week_number": 2,
      "year": 2025,
      "week_start_date": "2025-09-08",
      "week_end_date": "2025-09-14",
      "weekly_objective": "Complete Module 1 & 2 of AI Course",
      "focus_areas": [
        "Neural Networks",
        "Deep Learning",
        "Supervised Learning",
        "Unsupervised Learning",
        "Practical Exercises"
      ],
      "weekly_time_commitment": 480
    }
  ]
}

REQUIRED JSON STRUCTURE:
{
  "goal_id": "use the user's email or a UUID",
  "plan_description": "comprehensive description of the career transformation plan",
  "blockers": ["list of potential obstacles and challenges"],
  "milestones": [
    {
      "milestone_order": 1,
      "title": "milestone title",
      "description": "detailed description",
      "target_date": "YYYY-MM-DD"
    }
  ],
  "weekly_plans": [
    {
      "week_number": 1,
      "year": 2025,
      "week_start_date": "YYYY-MM-DD",
      "week_end_date": "YYYY-MM-DD",
      "weekly_objective": "objective for this week",
      "focus_areas": ["area1", "area2", "area3"],
      "weekly_time_commitment": 480
    }
  ]
}

Key Requirements:
1. Generate exactly 4 milestones with realistic target dates
2. Create exactly 12 weekly plans with detailed breakdowns
3. Each weekly plan should have maximum 5 focus areas
4. Include realistic time commitments (in minutes)
5. Ensure all dates are properly formatted (YYYY-MM-DD)
6. Return only valid JSON without any markdown formatting
7. Base the plan on the user's current situation, goals, and constraints
8. Use the user's email as goal_id or generate a UUID
9. Follow the example format and quality shown above""",
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
