# Generated by Django 5.2.4 on 2025-07-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerplan',
            name='goal_id',
            field=models.CharField(max_length=255),
        ),
    ]
